services:
  app:
    build:
      context: .
      args:
        INSTALL_TYPE: full
        GIT_REVISION: develop
    container_name: relecov_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /var/log/local/apps/relecov-platform:/opt/relecov-platform/logs:Z
      - relecov_documents:/opt/relecov-platform/documents
      - /opt/relecov-platform/static-host:/opt/relecov-platform/static:Z
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - relecov_net

  nextstrain:
    image: docker.io/nextstrain/base:latest
    container_name: relecov_nextstrain
    restart: unless-stopped
    command: ["nextstrain", "view", "/data", "--port", "8100", "--host", "0.0.0.0"]
    volumes:
      - nextstrain_data:/data
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    ports:
      - "8100:8100"
    networks:
      - relecov_net

  iskylims_app:
    build:
      context: ../relecov-iskylims
      args:
        INSTALL_TYPE: full
        GIT_REVISION: develop
    container_name: relecov_iskylims_app
    restart: unless-stopped
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
    ports:
      - "8001:8001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      relecov_net:
        aliases:
          - iskylimsapp

networks:
  relecov_net:

volumes:
  nextstrain_data:
