services:
  apache:
    container_name: relecov_apache
    restart: unless-stopped
    image: registry.access.redhat.com/ubi9/httpd-24
    depends_on:
      - app
      - nextstrain
      - iskylims_app
    ports:
      - "8081:8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - ${APACHE_CONF_PATH:-/srv/containers/bind/relecov-platform/relecov_apache_conf}/relecov_apache_reverse_proxy.conf:/etc/httpd/conf.d/01-relecov.conf:Z,ro
      - ${APACHE_CONF_PATH:-/srv/containers/bind/relecov-platform/relecov_apache_conf}/relecov_apache_logs.conf:/etc/httpd/conf.d/00-logformat.conf:Z,ro
      - ${APACHE_CONF_PATH:-/srv/containers/bind/relecov-platform/relecov_apache_conf}/relecov_apache_server-status.conf:/etc/httpd/conf.d/02-server-status.conf:Z,ro
      - ${APACHE_LOG_PATH:-/var/log/local/relecov-platform/apache}:/var/log/httpd:Z
      - relecov_static:${APP_INSTALL_PATH:-/opt/relecov-platform}/static:z,ro
      - relecov_documents:${APP_INSTALL_PATH:-/opt/relecov-platform}/documents:z,ro
      - iskylims_static:${ISKYLIMS_INSTALL_PATH:-/opt/iskylims}/static:z,ro
      - iskylims_documents:${ISKYLIMS_INSTALL_PATH:-/opt/iskylims}/documents:z,ro
    networks:
      - relecov_net

  app:
    build:
      context: .
      args:
        INSTALL_TYPE: ${INSTALL_TYPE:-full}
        GIT_REVISION: ${GIT_REVISION:-current}
        INSTALL_CONF: ${INSTALL_CONF:-conf/docker_production_settings.txt}
        APP_UID: ${APP_UID:-1212}
        APP_GID: ${APP_GID:-1212}
        APP_SHELL: ${APP_SHELL:-/sbin/nologin}
        APP_INSTALL_PATH: ${APP_INSTALL_PATH:-/opt/relecov-platform}
    container_name: relecov_app
    restart: unless-stopped
    expose:
      - "${APP_PORT:-8000}"
    environment:
      DJANGO_SETTINGS_MODULE: relecov_platform.settings
      DJANGO_DEBUG: ${DJANGO_DEBUG:-false}
      APP_MODE: prod
      APP_PORT: ${APP_PORT:-8000}
      DB_CONN_MAX_AGE: ${DB_CONN_MAX_AGE:-60}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY:-2}
      GUNICORN_THREADS: ${GUNICORN_THREADS:-2}
      GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT:-120}
      GUNICORN_KEEPALIVE: ${GUNICORN_KEEPALIVE:-5}
      APP_INSTALL_PATH: ${APP_INSTALL_PATH:-/opt/relecov-platform}
    user: "${APP_UID:-1212}:${APP_GID:-1212}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${PLATFORM_LOG_PATH:-/var/log/local/relecov-platform/apps}:${APP_INSTALL_PATH:-/opt/relecov-platform}/logs:Z
      - ${DJANGO_SETTINGS_PATH:-/srv/containers/bind/relecov-platform/relecov_django_setting/settings.py}:${APP_INSTALL_PATH:-/opt/relecov-platform}/relecov_platform/settings.py:Z
      - relecov_documents:${APP_INSTALL_PATH:-/opt/relecov-platform}/documents:z
      - relecov_static:${APP_INSTALL_PATH:-/opt/relecov-platform}/static:z
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    networks:
      - relecov_net

  nextstrain:
    image: docker.io/nextstrain/base:latest
    container_name: relecov_nextstrain
    restart: unless-stopped
    command: ["nextstrain", "view", "/data", "--port", "${NEXTSTRAIN_PORT:-8100}", "--host", "0.0.0.0"]
    volumes:
      - nextstrain_data:/data
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    expose:
      - "${NEXTSTRAIN_PORT:-8100}"
    networks:
      - relecov_net

  iskylims_app:
    build:
      context: ../relecov-iskylims
      args:
        INSTALL_TYPE: ${ISKYLIMS_INSTALL_TYPE:-full}
        GIT_REVISION: ${ISKYLIMS_GIT_REVISION:-current}
        INSTALL_CONF: ${ISKYLIMS_INSTALL_CONF:-conf/docker_production_settings.txt}
        INSTALL_PATH: ${ISKYLIMS_INSTALL_PATH:-/opt/iskylims}
        APP_UID: ${APP_UID:-1212}
        APP_GID: ${APP_GID:-1212}
        APP_SHELL: ${APP_SHELL:-/sbin/nologin}
    container_name: relecov_iskylims_app
    restart: unless-stopped
    expose:
      - "${ISKYLIMS_APP_PORT:-8001}"
    volumes:
      - ${ISKYLIMS_LOG_PATH:-/var/log/local/relecov-iskylims/apps}:${ISKYLIMS_INSTALL_PATH:-/opt/iskylims}/logs:Z
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - iskylims_static:${ISKYLIMS_INSTALL_PATH:-/opt/iskylims}/static:z
      - iskylims_documents:${ISKYLIMS_INSTALL_PATH:-/opt/iskylims}/documents:z
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      relecov_net:
        aliases:
          - iskylimsapp

networks:
  relecov_net:

volumes:
  nextstrain_data:
  relecov_static:
  relecov_documents:
  iskylims_documents:
  iskylims_static:
