# Generated by Django 5.2.15 on 2026-08-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GraphicJsonFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("graphic_name", models.CharField(max_length=60)),
                ("graphic_data", models.JSONField()),
                ("creation_date", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "dashboard_graphic_json_file",
            },
        ),
    ]
