# Apache reverse proxy config for RELECOV Platform production container

<VirtualHost *:8000>
    ServerName relecov-platform.isciiides.es

    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "http"
    RequestHeader set X-Forwarded-Port "8000"

    ProxyPass /static !
    Alias /static __APP_INSTALL_PATH__/static
    <Directory __APP_INSTALL_PATH__/static>
        Require all granted
    </Directory>

    ProxyPass /documents !
    Alias /documents __APP_INSTALL_PATH__/documents
    <Directory __APP_INSTALL_PATH__/documents>
        Require all granted
    </Directory>

    ProxyPass / http://app:8000/
    ProxyPassReverse / http://app:8000/

    ErrorLog /var/log/httpd/relecov-apache.error.log
    CustomLog /var/log/httpd/relecov-apache.access.log combined
</VirtualHost>
