# Apache reverse proxy config for RELECOV services

<VirtualHost *:8080>
    ServerName relecov-platform.isciiides.es

    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "http"
    RequestHeader set X-Forwarded-Port "8090"

    ProxyPass /static !
    Alias /static /opt/relecov-platform/static
    <Directory /opt/relecov-platform/static>
        Require all granted
    </Directory>

    ProxyPass /documents !
    Alias /documents /opt/relecov-platform/documents
    <Directory /opt/relecov-platform/documents>
        Require all granted
    </Directory>

    ProxyPass / http://app:8000/
    ProxyPassReverse / http://app:8000/

    ErrorLog /var/log/httpd/relecov-platform.error.log
    CustomLog /var/log/httpd/relecov-platform.access.log combined
</VirtualHost>

<VirtualHost *:8080>
    ServerName nextstrain.isciiides.es

    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "http"
    RequestHeader set X-Forwarded-Port "8090"

    ProxyPass / http://nextstrain:8100/
    ProxyPassReverse / http://nextstrain:8100/

    ErrorLog /var/log/httpd/relecov-nextstrain.error.log
    CustomLog /var/log/httpd/relecov-nextstrain.access.log combined
</VirtualHost>

<VirtualHost *:8080>
    ServerName relecov-iskylims.isciiides.es

    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "http"
    RequestHeader set X-Forwarded-Port "8090"

    ProxyPass /static !
    Alias /static /opt/iskylims/static
    <Directory /opt/iskylims/static>
        Require all granted
    </Directory>

    ProxyPass /documents !
    Alias /documents /opt/iskylims/documents
    <Directory /opt/iskylims/documents>
        Require all granted
    </Directory>

    ProxyPass / http://iskylimsapp:8001/
    ProxyPassReverse / http://iskylimsapp:8001/

    ErrorLog /var/log/httpd/relecov-iskylims.error.log
    CustomLog /var/log/httpd/relecov-iskylims.access.log combined
</VirtualHost>