# Apache reverse proxy config for RELECOV services

<VirtualHost *:8081>
    ServerName __RELECOV_PLATFORM_SERVER_NAME__

    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "__RELECOV_FORWARDED_PROTO__"
    RequestHeader set X-Forwarded-Port "__RELECOV_FORWARDED_PORT__"
    RequestHeader set X-Forwarded-Host "__RELECOV_PLATFORM_SERVER_NAME__"

    LimitRequestBody 52428800
    <IfModule security2_module>
        SecRequestBodyLimit 52428800
        SecRequestBodyNoFilesLimit 52428800
    </IfModule>

    ProxyPass /static !
    Alias /static __RELECOV_PLATFORM_INSTALL_PATH__/static
    <Directory __RELECOV_PLATFORM_INSTALL_PATH__/static>
        Require all granted
    </Directory>

    ProxyPass /documents !
    Alias /documents __RELECOV_PLATFORM_INSTALL_PATH__/documents
    <Directory __RELECOV_PLATFORM_INSTALL_PATH__/documents>
        Require all granted
    </Directory>

    ProxyPass / http://app:__RELECOV_PLATFORM_APP_PORT__/
    ProxyPassReverse / http://app:__RELECOV_PLATFORM_APP_PORT__/
    ProxyTimeout __GUNICORN_TIMEOUT__
    TimeOut __GUNICORN_TIMEOUT__

    CustomLog logs/__RELECOV_PLATFORM_LOG_NAME__-apache.access.log combined env=!forwarded
    CustomLog logs/__RELECOV_PLATFORM_LOG_NAME__-apache.access.log proxy env=forwarded
    ErrorLog logs/__RELECOV_PLATFORM_LOG_NAME__-apache.error.log
</VirtualHost>

<VirtualHost *:8081>
    ServerName __RELECOV_NEXTSTRAIN_SERVER_NAME__

    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "__RELECOV_FORWARDED_PROTO__"
    RequestHeader set X-Forwarded-Port "__RELECOV_FORWARDED_PORT__"
    RequestHeader set X-Forwarded-Host "__RELECOV_NEXTSTRAIN_SERVER_NAME__"

    ProxyPass / http://nextstrain:__RELECOV_NEXTSTRAIN_PORT__/
    ProxyPassReverse / http://nextstrain:__RELECOV_NEXTSTRAIN_PORT__/
    ProxyTimeout __GUNICORN_TIMEOUT__
    TimeOut __GUNICORN_TIMEOUT__

    CustomLog logs/__RELECOV_NEXTSTRAIN_LOG_NAME__-apache.access.log combined env=!forwarded
    CustomLog logs/__RELECOV_NEXTSTRAIN_LOG_NAME__-apache.access.log proxy env=forwarded
    ErrorLog logs/__RELECOV_NEXTSTRAIN_LOG_NAME__-apache.error.log
</VirtualHost>

<VirtualHost *:8081>
    ServerName __RELECOV_ISKYLIMS_SERVER_NAME__

    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "__RELECOV_FORWARDED_PROTO__"
    RequestHeader set X-Forwarded-Port "__RELECOV_FORWARDED_PORT__"
    RequestHeader set X-Forwarded-Host "__RELECOV_ISKYLIMS_SERVER_NAME__"

    LimitRequestBody 52428800
    <IfModule security2_module>
        SecRequestBodyLimit 52428800
        SecRequestBodyNoFilesLimit 52428800
    </IfModule>

    ProxyPass /static !
    Alias /static __RELECOV_ISKYLIMS_INSTALL_PATH__/static
    <Directory __RELECOV_ISKYLIMS_INSTALL_PATH__/static>
        Require all granted
    </Directory>

    ProxyPass /documents !
    Alias /documents __RELECOV_ISKYLIMS_INSTALL_PATH__/documents
    <Directory __RELECOV_ISKYLIMS_INSTALL_PATH__/documents>
        Require all granted
    </Directory>

    ProxyPass / http://iskylimsapp:__RELECOV_ISKYLIMS_APP_PORT__/
    ProxyPassReverse / http://iskylimsapp:__RELECOV_ISKYLIMS_APP_PORT__/
    ProxyTimeout __GUNICORN_TIMEOUT__
    TimeOut __GUNICORN_TIMEOUT__

    CustomLog logs/__RELECOV_ISKYLIMS_LOG_NAME__-apache.access.log combined env=!forwarded
    CustomLog logs/__RELECOV_ISKYLIMS_LOG_NAME__-apache.access.log proxy env=forwarded
    ErrorLog logs/__RELECOV_ISKYLIMS_LOG_NAME__-apache.error.log
</VirtualHost>
